### ISSUE TITLE
libgcrypt11 cannot be resolved in openSUSE 13.2

### ISSUE THREAD

**Issue by dradtke** [aspiers/opensuse-spotify-installer#38] opened 2015-04-20 19:08 UTC
openSUSE 13.2 only has `libgcrypt20` available, but Spotify requires `libgcrypt11` to be installed. I guess my previous attempt worked fine because I was working with a system that was upgraded from 13.1, but after trying to install Spotify on a fresh 13.2, I had to manually install `libgcrypt11` in order for the build to succeed.

No pull request for this because I don't know what the best approach would be. Perhaps use zypper to check for the existence of `libgcrypt11` on the system, and if it's not found install it from the build service before continuing to build Spotify.

**Comment by aspiers** [comment] 2015-04-22 23:24
Yes, that sounds reasonable.

**Comment by aspiers** [comment] 2015-04-22 23:26
This is actually a duplicate of #33 - closing.

**Closed by aspiers** 2015-04-22 23:26 UTC
